version: '3'

tasks:
  install-chaos-mesh:
    desc: Install Chaos Mesh using Helm (idempotent)
    cmds:
      - helm repo add chaos-mesh https://charts.chaos-mesh.org
      - |
        if ! kubectl get ns chaos-mesh &> /dev/null; then
          kubectl create ns chaos-mesh
        fi
      - |
        if ! helm status chaos-mesh -n chaos-mesh &> /dev/null; then
          helm install chaos-mesh chaos-mesh/chaos-mesh -n chaos-mesh --version 2.7.2
        fi
      - kubectl get pods --namespace chaos-mesh -l app.kubernetes.io/instance=chaos-mesh
  
  uninstall-chaos-mesh:
    desc: Uninstall Chaos Mesh and clean up resources (idempotent)
    cmds:
      - |
        if helm status chaos-mesh -n chaos-mesh &> /dev/null; then
          helm uninstall chaos-mesh -n chaos-mesh
        fi
      - |
        if kubectl get ns chaos-mesh &> /dev/null; then
          kubectl get pods --namespace chaos-mesh -l app.kubernetes.io/instance=chaos-mesh || true
          kubectl delete ns chaos-mesh
        fi
      - kubectl get pods --namespace chaos-mesh -l app.kubernetes.io/instance=chaos-mesh || true
