consensusNodes:
  - name: node1
    account: 0.0.3
    endpoint: localhost:30211
  - name: node2
    account: 0.0.4
    endpoint: localhost:30212
  - name: node3
    account: 0.0.5
    endpoint: localhost:30213
  - name: node4
    account: 0.0.6
    endpoint: localhost:30214
  - name: node5
    account: 0.0.7
    endpoint: localhost:30215
mirrorNodes:
  - name: mirror1
    endpoint: localhost:8080
operator:
  account: 0.0.2
  key: "302e020100300506032b65700422042091132178e72057a1d7528025956fe39b0b847f200ab59b2fdd367017f3087137"