apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: solo-chaos-network-bandwidth-${UUID}
  namespace: chaos-mesh
spec:
  action: bandwidth
  mode: all
  selector:
    namespaces:
      - ${NAMESPACE}
    expressionSelectors:
      - key: solo.hedera.com/node-name
        operator: In
        values: [${NODE_NAMES}]
    labelSelectors:
      'solo.hedera.com/type': 'network-node'
  bandwidth:
    rate: ${RATE}
    limit: ${LIMIT}
    buffer: ${BUFFER}
