apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: solo-chaos-network-netem-us-to-us
  namespace: chaos-mesh
spec:
  action: netem
  mode: all
  selector:
    namespaces:
      - ${NAMESPACE}
    labelSelectors:
      'solo.hedera.com/type': 'network-node'
      'solo.hedera.com/region': 'us'
  target:
    mode: all
    selector:
      namespaces:
        - ${NAMESPACE}
      labelSelectors:
        'solo.hedera.com/type': 'network-node'
        'solo.hedera.com/region': 'us'
  delay:
    latency: '10ms'    # us <-> us: 20ms RTT (10ms one-way intra-region)
    correlation: '80'
    jitter: '5ms'
  rate:
    rate: '1gbps'
---
# US to EU latency (50ms one-way for 100ms RTT)
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: solo-chaos-network-netem-us-to-eu
  namespace: chaos-mesh
spec:
  action: netem
  mode: all
  selector:
    namespaces:
      - ${NAMESPACE}
    labelSelectors:
      'solo.hedera.com/type': 'network-node'
      'solo.hedera.com/region': 'us'
  target:
    mode: all
    selector:
      namespaces:
        - ${NAMESPACE}
      labelSelectors:
        'solo.hedera.com/type': 'network-node'
        'solo.hedera.com/region': 'eu'
  delay:
    latency: '50ms'    # us <-> eu: 100ms RTT (50ms one-way)
    correlation: '80'
    jitter: '10ms'
  rate:
    rate: '1gbps'
---
# US to AP latency (100ms one-way for 200ms RTT)
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: solo-chaos-network-netem-us-to-ap
  namespace: chaos-mesh
spec:
  action: netem
  mode: all
  selector:
    namespaces:
      - ${NAMESPACE}
    labelSelectors:
      'solo.hedera.com/type': 'network-node'
      'solo.hedera.com/region': 'us'
  target:
    mode: all
    selector:
      namespaces:
        - ${NAMESPACE}
      labelSelectors:
        'solo.hedera.com/type': 'network-node'
        'solo.hedera.com/region': 'ap'
  delay:
    latency: '100ms'   # us <-> ap: 200ms RTT (100ms one-way)
    correlation: '80'
    jitter: '20ms'
  rate:
    rate: '1gbps'
