name: "ZXC: Unit Test"
on:
  workflow_call:
    inputs:
      go-version:
        description: "Go Version:"
        type: string
        required: false
        default: ">=1.25.0"
      custom-job-label:
        description: "Custom Job Label:"
        type: string
        required: false
        default: "Unit Test"

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  unit-test:
    name: "${{ inputs.custom-job-label || 'Unit Test' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.39.2
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup GoLang
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run Unit Tests
        run: task test:unit

      - name: Unit Test Report
        if: ${{ always() }}
        run: |
          if [[ -f unit-test-report.md ]]; then
            cat unit-test-report.md >> "${GITHUB_STEP_SUMMARY}"
          fi
